#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# currently the easiest way to use the nodejs asdf plugin https://github.com/asdf-vm/asdf-nodejs
export NODEJS_CHECK_SIGNATURES="no"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  --plugin-dir dotbot-brew \
  --plugin-dir dotbot-vscode \
  --plugin-dir dotbot-asdf \
  -c "${CONFIG}" "${@}"

